<a href="https://colab.research.google.com/github/DayeongJung/dataPractice/blob/main/dataAirline/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
pd.read_csv('https://raw.githubusercontent.com/DayeongJung/dataPractice/main/dataAirline/kosis_airline_company.csv',encoding='CP949')

           시점  항공사별(1) 도착출발별(1)  운항 (편)   여객 (명)  화물 (톤)
0     2005.01   아시아나항공       도착    6613   791439   28012
1     2005.01   아시아나항공       출발    6610   799835   29576
2     2005.01     대한항공       도착    8869  1372897   70544
3     2005.01     대한항공       출발    8870  1405847   78329
4     2005.01      외항사       도착    3145   443386   28311
...       ...      ...      ...     ...      ...     ...
3811  2024.01  에어로케이항공       출발     368    59744     416
3812  2024.01   에어프레미아       도착     123    32236    1109
3813  2024.01   에어프레미아       출발     122    36071    1557
3814  2024.01      외항사       도착    7336  1061718   50335
3815  2024.01      외항사       출발    7348  1141378   51525

[3816 rows x 6 columns]